version: "3.7"

services:
  # MySQL
  db:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql:z
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=project
      - MYSQL_USER=project
      - MYSQL_PASSWORD=project

  # Nginx
  server:
    image: nicolashuber/nginx
    links:
      - laravel
    ports:
      - 80:80
    volumes:
      - ${WORKING_DIR}:/app

  # PHP FPM
  laravel:
    image: nicolashuber/php-fpm
    volumes:
      - ${WORKING_DIR}:/app
    links:
      - db
      - redis

  # PHP
  php:
    image: nicolashuber/php-cli
    entrypoint: ["php"]
    depends_on:
      - db

  # Composer
  composer:
    image: composer
    volumes:
      # Map local user Composer directory with container for cache packages
      - ~/.docker_cache/composer:/tmp/cache:z
    working_dir: /app

  # Node with NPM/Yarn/npx
  node:
    image: node
    working_dir: /app

  # redis
  redis:
    image: redis
    ports:
      - 6379:6379

  # phpcs
  phpcs:
    image: herloct/phpcs
    command: ["--standard=PSR1,PSR2", "--ignore=*/vendor/,*/tests/,database/,app/bootstrap/,public/", "--colors", "."]
    working_dir: /app

volumes:
  mysql_data:
    name: ${VOLUME_PREFIX}mysql_data
