#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use Laranexus\Laranexus;

require __DIR__ . '/../vendor/autoload.php';

$laranexus = new Laranexus();
$laranexus->setWorkingDir(getcwd());
$app = new Application();

$kernel = [
    \Laranexus\Commands\Composer::class,
    \Laranexus\Commands\Artisan::class,
    \Laranexus\Commands\Install::class,
    \Laranexus\Commands\Create::class,
    \Laranexus\Commands\Server::class,
    \Laranexus\Commands\Down::class,
    \Laranexus\Commands\Npm::class,
    \Laranexus\Commands\Dev::class,
];

foreach ($kernel as $cmd) {
    $app->add(new $cmd($laranexus));
}

$app->run();
